topics_dict = {
    "Benefits of AI in education": {
        "supportive": "I think AI in education is a great step forward because it makes learning personal for every student. Not everyone learns the same way or at the same speed, right? AI-powered platforms can change the lessons to fit each student's needs, giving extra help where they struggle and moving faster where they do well. Plus, it saves teachers a lot of time by handling boring tasks like grading multiple-choice tests or tracking attendance. This means teachers can focus on what really matters: guiding students, having good discussions, and giving that human touch that a machine can't. Also, students can get help anytime, 24/7, from AI tutors or chatbots, so they don't get stuck on homework until the next day. This makes education more flexible and accessible for everyone.",
        "against": "a big worry is that too much AI might make students lazy. If a student can just ask an AI for the answer to an essay or a math problem, they might not develop their critical thinking and problem-solving skills. The human element is also very important. Teachers provide emotional support, mentorship, and can understand a student's background and feelings, which an AI cannot do. There are also practical problems like the digital divide; not all students have access to the internet or devices needed for these AI tools, which could make the gap between rich and poor students even bigger. And we have to think about privacy—AI systems collect tons of student data, which raises serious security concerns if it's not protected properly.",
        "balanced": "the best way forward is probably a balanced approach. AI shouldn't replace teachers; it should be a powerful tool in their hands. We should use AI to do the repetitive work and provide data-driven insights to help teachers understand student needs better. Teachers can then use that extra time to focus on complex skills like creativity, collaboration, and emotional development, which need human interaction. It's crucial that we put strict rules in place to protect student data and make sure AI systems are fair and don't have any hidden biases. If we can find the right mix of technology and human guidance, we can make education better and more inclusive for everyone."
    },
    "Impact of social media": {
        "supportive": "I think social media is mostly a good thing. First, it connects people across the globe, letting us talk to family and friends instantly, no matter where they are [2]. It also helps us learn new things and find information fast; you can follow experts and get updates on news or world events right away [2]. For businesses, it's a great tool for growth and reaching customers easily [2]. Plus, it gives ordinary people a powerful voice to raise awareness about important issues or causes they care about, which strengthens democracy [2].",
        "against": "Honestly, social media has some serious drawbacks. The biggest one for me is the negative effect on mental health. Seeing perfect lives online often makes people feel insecure or anxious, and cyberbullying is a huge problem [2]. It's also a major source of fake news and misinformation, which can spread like wildfire and cause real harm [2]. Another issue is that it can be a huge time-waster and a big distraction from real work or study, leading to less face-to-face interaction and shallower relationships ",
        "balanced": "it's not all good or all bad; it's a mix. Social media provides amazing opportunities for connection and learning, but we have to be smart about how we use it [2]. The key is balance. We need to set limits on our screen time and be critical of the information we see, always double-checking the facts [2]. It’s a powerful tool, and like any tool, its impact depends entirely on the user. If we use it responsibly, the benefits can outweigh the risks; if not, the problems can be significant "
    },
    "Do deadlines destroy creativity?": {
        "supportive": "Yes, deadlines often kill creativity. True creative work needs flow and time to breathe. When a clock is ticking, people focus on just finishing the task, not on original or innovative ideas. The pressure makes us take the easy, standard route rather than experimenting, which is the heart of creativity.",
        "against": "I disagree; deadlines are actually good for creativity. They force us to stop overthinking and start producing. Deadlines create urgency and focus, preventing endless delays and procrastination. Often, our most innovative solutions come when we have limited time and resources, forcing us to think differently.",
        "balanced": "Deadlines can be a double-edged sword. While extreme, rigid deadlines can stifle the creative process, reasonable deadlines provide necessary structure and motivation. The key is balance: giving enough time for exploration but also setting a clear target to ensure things actually get done."
    },
    # Add all remaining topics in the same format
    "India's wedding industry": {
        "supportive": "India's wedding industry is a massive economic engine. It creates millions of jobs for everyone from decorators and caterers to local artisans and small business owners. It is a vital part of our culture and helps drive significant consumer spending, contributing hugely to the GDP.",
        "against": "the industry promotes immense waste and unnecessary extravagance. The pressure to have a big fat wedding puts huge financial stress on families, often leading to debt. This lavish spending on a single event is not sustainable and highlights wealth inequality in the country.",
        "balanced": "The wedding industry is undeniably important culturally and economically. The challenge isn't the industry itself, but the mindset of excess. We need to encourage more responsible spending and sustainable practices. Celebrating our culture is fine, but it shouldn’t lead to financial ruin or environmental damage."
    }
}
